{
 "title": "Kafka/Flink/MySQL Sensors demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "All CEPs detected",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measure": "avg_temperature",
     "rawSql": "SELECT\n  event_time AS \"time\", history, elapsed, non_errors,\n  avg_temperature, max_temperature, min_temperature\nFROM cep_data\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "CEPs over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "measure": "max_temperature",
     "rawSql": "SELECT\n  event_time AS \"time\",\n  avg_temperature\nFROM cep_data\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperature readings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawQuery": "SELECT * FROM $__database.$__table WHERE $__timeFilter order by time\n\n\n\n\n\n\n",
     "rawSql": "SELECT\n  $__time(ptime),\n  temperature\nFROM\n  sensors\nWHERE\n  $__timeFilter(ptime)\n"
    }
   ]
  },
  {
   "title": "CountByStatus",
   "type": "stat",
   "description": "Count the number of hosts per micro-service in a specific region.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measure": "temperature",
     "rawSql": "SELECT CASE WHEN status = 'OK' THEN total ELSE NULL END AS STATUS_OK,\nCASE WHEN status = 'WARNING' THEN total ELSE NULL END AS STATUS_WARNING,\nCASE WHEN status = 'ERROR' THEN total ELSE NULL END AS STATUS_ERROR\nFROM (  SELECT status, COUNT(*) as total FROM sensors WHERE $__timeFilter(ptime)  GROUP BY status    ) as t"
    }
   ]
  },
  {
   "title": "Standard deviation on temperature. 30 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measure": "temperature",
     "rawSql": "SELECT $__time(ptime), stddev_samp(temperature)\nFROM (SELECT ptime, temperature FROM sensors\nWHERE\n  $__timeFilter(ptime)\n  ) as T\ngroup by ptime\n\n\n"
    }
   ]
  },
  {
   "title": "MAX temperature in past 10 seconds",
   "type": "table",
   "gridPos": { "h": 48, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "measure": "temperature",
     "rawSql": "SELECT sensors.sensor_id, ptime, temperature, status \nFROM sensors INNER JOIN ( SELECT sensor_id, MAX(ptime) AS maxsign FROM sensors GROUP BY sensor_id ) ms ON sensors.sensor_id = ms.sensor_id AND ptime = maxsign order by sensors.sensor_id"
    }
   ]
  },
  {
   "title": "All sensors MAX temperatures in interval",
   "type": "table",
   "gridPos": { "h": 48, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measure": "temperature",
     "rawSql": "SELECT\n  MAX(temperature) as max_temperature,\n  sensor_id\nFROM\n  sensors\nWHERE\n  $__timeFilter(ptime)\nGROUP BY sensor_id\norder by max_temperature DESC\n"
    }
   ]
  }
 ]
}